In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

## **Data Gathering**

In [ ]:
df=pd.read_csv("https://drive.google.com/uc?id=1q5OsZDzQWmie0kp5SwXFN8NyJ_qkJf7T")

In [ ]:
df.shape

(302010, 30)

In [ ]:
# here some columns was not showed so i used display.max_columns to see all columns data in my dataframe
pd.set_option('display.max_columns', None)

In [ ]:
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,21.0,Male,Low,Regular,9/18/2023,2023.0,September,22:03:55,3.0,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,19.0,Female,Low,Premium,12/31/2023,2023.0,December,8:42:04,2.0,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,48.0,Male,Low,Regular,4/26/2023,2023.0,April,4:06:29,3.0,354.477600,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,56.0,Male,High,Premium,5/8/2023,2023.0,May,14:55:17,7.0,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,22.0,Male,Low,Premium,1/10/2024,2024.0,January,16:54:07,2.0,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [ ]:
df.tail()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
302005,4246475.0,12104.0,Meagan Ellis,Courtney60@gmail.com,7.466354e+09,389 Todd Path Apt. 159,Townsville,New South Wales,4567.0,Australia,31.0,Male,Medium,Regular,1/20/2024,2024.0,January,23:40:29,5.0,194.792597,973.962984,Books,Penguin Books,Fiction,Bad,Same-Day,Cash,Processing,1.0,Historical fiction
302006,1197603.0,69772.0,Mathew Beck,Jennifer71@gmail.com,5.754305e+09,52809 Mark Forges,Hanover,Berlin,16852.0,Germany,35.0,Female,Low,New,12/28/2023,2023.0,December,2:55:45,1.0,285.137301,285.137301,Electronics,Apple,Laptop,Excellent,Same-Day,Cash,Processing,5.0,LG Gram
302007,7743242.0,28449.0,Daniel Lee,Christopher100@gmail.com,9.382530e+09,407 Aaron Crossing Suite 495,Brighton,England,88038.0,UK,41.0,Male,Low,Premium,2/27/2024,2024.0,February,2:43:49,3.0,60.701761,182.105285,Clothing,Adidas,Jacket,Average,Express,Cash,Shipped,2.0,Parka
302008,9301950.0,45477.0,Patrick Wilson,Rebecca65@gmail.com,9.373222e+09,3204 Baird Port,Halifax,Ontario,67608.0,Canada,41.0,Male,Medium,New,9/3/2023,2023.0,September,11:20:31,1.0,120.834784,120.834784,Home Decor,IKEA,Furniture,Good,Standard,Cash,Shipped,4.0,TV stand
302009,2882826.0,53626.0,Dustin Merritt,William14@gmail.com,9.518927e+09,143 Amanda Crescent,Tucson,West Virginia,25242.0,USA,28.0,Female,Low,Premium,1/8/2024,2024.0,January,11:44:36,7.0,340.319059,2382.233417,Home Decor,Home Depot,Decorations,Average,Same-Day,Cash,Shipped,2.0,Clocks

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302010 entries, 0 to 302009
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    301677 non-null  float64
 1   Customer_ID       301702 non-null  float64
 2   Name              301628 non-null  object
 3   Email             301663 non-null  object
 4   Phone             301648 non-null  float64
 5   Address           301695 non-null  object
 6   City              301762 non-null  object
 7   State             301729 non-null  object
 8   Zipcode           301670 non-null  float64
 9   Country           301739 non-null  object
 10  Age               301837 non-null  float64
 11  Gender            301693 non-null  object
 12  Income            301720 non-null  object
 13  Customer_Segment  301795 non-null  object
 14  Date              301651 non-null  object
 15  Year              301660 non-null  float64
 16  Month             301737 non-null  object
 17  Time              301660 non-null  object
 18  Total_Purchases   301649 non-null  float64
 19  Amount            301653 non-null  float64
 20  Total_Amount      301660 non-null  float64
 21  Product_Category  301727 non-null  object
 22  Product_Brand     301729 non-null  object
 23  Product_Type      302010 non-null  object
 24  Feedback          301826 non-null  object
 25  Shipping_Method   301673 non-null  object
 26  Payment_Method    301713 non-null  object
 27  Order_Status      301775 non-null  object
 28  Ratings           301826 non-null  float64
 29  products          302010 non-null  object
dtypes: float64(10), object(20)
memory usage: 69.1+ MB

### **Drop Unwanted Columns**

In [ ]:
cols_to_drop = ['Name', 'Email', 'Phone', 'Address', 'Zipcode']

# Store original shape before drop for logging
shape_before = df.shape

# Drop columns
df.drop(columns=cols_to_drop, inplace=True)

# Verify
shape_after = df.shape

print(f"Columns dropped : {cols_to_drop}")
print(f"Shape before    : {shape_before}")
print(f"Shape after     : {shape_after}")
print(f"Columns removed : {shape_before[1] - shape_after[1]}")
print(f"\nRemaining columns ({shape_after[1]}):")
print(df.columns.tolist())

Columns dropped : ['Name', 'Email', 'Phone', 'Address', 'Zipcode']
Shape before    : (302010, 30)
Shape after     : (302010, 25)
Columns removed : 5

Remaining columns (25):
['Transaction_ID', 'Customer_ID', 'City', 'State', 'Country', 'Age', 'Gender', 'Income', 'Customer_Segment', 'Date', 'Year', 'Month', 'Time', 'Total_Purchases', 'Amount', 'Total_Amount', 'Product_Category', 'Product_Brand', 'Product_Type', 'Feedback', 'Shipping_Method', 'Payment_Method', 'Order_Status', 'Ratings', 'products']

In [ ]:
df.head()

,Transaction_ID,Customer_ID,City,State,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Dortmund,Berlin,Germany,21.0,Male,Low,Regular,9/18/2023,2023.0,September,22:03:55,3.0,108.028757,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Nottingham,England,UK,19.0,Female,Low,Premium,12/31/2023,2023.0,December,8:42:04,2.0,403.353907,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Geelong,New South Wales,Australia,48.0,Male,Low,Regular,4/26/2023,2023.0,April,4:06:29,3.0,354.477600,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Edmonton,Ontario,Canada,56.0,Male,High,Premium,5/8/2023,2023.0,May,14:55:17,7.0,352.407717,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Bristol,England,UK,22.0,Male,Low,Premium,1/10/2024,2024.0,January,16:54:07,2.0,124.276524,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

### **Handle Duplicates**

In [ ]:
df.duplicated().sum()

np.int64(4)

In [ ]:
# Full Duplicate Rows
shape_before_full = df.shape
df.drop_duplicates(keep='first', inplace=True)
shape_after_full = df.shape

full_dupes_removed = shape_before_full[0] - shape_after_full[0]
print(f"Full Duplicate Rows")
print(f"Shape before : {shape_before_full}")
print(f"Shape after  : {shape_after_full}")
print(f"Rows removed : {full_dupes_removed}")

Full Duplicate Rows
Shape before : (302010, 25)
Shape after  : (302006, 25)
Rows removed : 4

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Transaction_ID'].duplicated().sum()

np.int64(7544)

In [ ]:
# Duplicate Transaction IDs
shape_before_tid = df.shape
df.drop_duplicates(subset=['Transaction_ID'], keep='first', inplace=True)
shape_after_tid = df.shape

tid_dupes_removed = shape_before_tid[0] - shape_after_tid[0]
print(f"\nDuplicate Transaction IDs")
print(f"Shape before : {shape_before_tid}")
print(f"Shape after  : {shape_after_tid}")
print(f"Rows removed : {tid_dupes_removed}")

Duplicate Transaction IDs
Shape before : (302006, 25)
Shape after  : (294462, 25)
Rows removed : 7544

In [ ]:
# Final Summary
print(f"\nDuplicate Cleaning Summary")
print(f"Total rows removed : {full_dupes_removed + tid_dupes_removed}")
print(f"Final shape        : {df.shape}")

Duplicate Cleaning Summary
Total rows removed : 7548
Final shape        : (294462, 25)

In [ ]:
df['Transaction_ID'].duplicated().sum()

np.int64(0)

## **Datatype Fixing**

In [ ]:
# ID Columns
df['Transaction_ID'] = df['Transaction_ID'].astype('Int64')
df['Customer_ID'] = df['Customer_ID'].astype('Int64')

print(df[['Transaction_ID', 'Customer_ID']].dtypes)
print(df[['Transaction_ID', 'Customer_ID']].isnull().sum())

Transaction_ID    Int64
Customer_ID       Int64
dtype: object
Transaction_ID      1
Customer_ID       296
dtype: int64

In [ ]:
# Date Column
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month_name()

print("Date dtype :", df['Date'].dtype)
print("Year dtype :", df['Year'].dtype)
print("\nAll months present:")
print(df['Month'].value_counts())

Date dtype : datetime64[ns]
Year dtype : float64

All months present:
Month
January      24994
March        24977
October      24977
July         24904
August       24856
December     24718
May          24582
September    24265
June         24190
April        24131
November     24023
February     23494
Name: count, dtype: int64

In [ ]:
# Time Column
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S', errors='coerce').dt.time

print(df['Time'].dtype)
print(df['Time'].isnull().sum())
print(df['Time'].head(5))

object
336
0    22:03:55
1    08:42:04
2    04:06:29
3    14:55:17
4    16:54:07
Name: Time, dtype: object

In [ ]:
# Fix numerical Column
df['Age'] = df['Age'].astype('Int64')
df['Year'] = df['Year'].astype('Int64')
df['Total_Purchases'] = df['Total_Purchases'].astype('Int64')
df['Ratings'] = df['Ratings'].astype('Int64')

In [ ]:
# Roundoff float Column
df['Amount'] = df['Amount'].round(2)
df['Total_Amount'] = df['Total_Amount'].round(2)

In [ ]:
# Categorical Column
cat_cols = [
    'City','State','Country','Gender','Income','Customer_Segment',
    'Product_Category','Product_Brand','Product_Type',
    'Feedback','Shipping_Method','Payment_Method','Order_Status','products'
]

for col in cat_cols:
    df[col] = df[col].astype('category')

In [ ]:
# Month Column
df['Month'] = pd.Categorical(
    df['Month'],
    categories=[
        'January','February','March','April','May','June',
        'July','August','September','October','November','December'
    ],
    ordered=True
)

### **Handle missing values**

In [ ]:
# Check null values
df.isnull().sum()

Transaction_ID        1
Customer_ID         296
City                244
State               271
Country             266
Age                 169
Gender              310
Income              282
Customer_Segment    208
Date                351
Year                351
Month               351
Time                336
Total_Purchases     354
Amount              347
Total_Amount        343
Product_Category    275
Product_Brand       270
Product_Type          0
Feedback            180
Shipping_Method     330
Payment_Method      290
Order_Status        232
Ratings             180
products              0
dtype: int64

In [ ]:
# Drop rows
df = df.dropna(subset=['Transaction_ID','Customer_ID','Amount'])

In [ ]:
# Numerical Imputation
num_cols = ['Age','Ratings']

for col in num_cols:
   df[col].fillna(df[col].median(), inplace=True)

/tmp/ipykernel_5015/966887336.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipykernel_5015/966887336.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
# Categorical Imputation
cat_cols = ['Gender','Customer_Segment','Product_Category',
            'Product_Brand','Feedback','Shipping_Method',
            'Payment_Method','Order_Status','City','State','Country','Income']

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_5015/3660209747.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [ ]:
# Handle missing values Total_Purchases, Amount, Total_Amount
df[df[['Total_Purchases', 'Amount', 'Total_Amount']].isnull().any(axis=1)]

,Transaction_ID,Customer_ID,City,State,Country,Age,Gender,Income,Customer_Segment,Date,Year,Month,Time,Total_Purchases,Amount,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
174,8744927,39728,Portsmouth,England,UK,50,Male,High,Regular,2023-07-23,2023,July,20:46:04,<NA>,417.03,1251.10,Grocery,Pepsi,Water,Average,Standard,Credit Card,Pending,2,Sparkling water
582,6188453,92425,Portsmouth,England,UK,48,Male,High,Regular,2023-11-29,2023,November,07:59:04,4,472.63,NaN,Electronics,Sony,Television,Good,Same-Day,PayPal,Shipped,4,Plasma TV
966,1153740,13769,Portsmouth,England,UK,21,Female,High,Regular,2023-03-07,2023,March,10:24:29,6,487.03,NaN,Clothing,Adidas,Jacket,Average,Standard,PayPal,Pending,2,Blazer
1039,9168609,45787,Portsmouth,England,UK,21,Male,High,Regular,2023-07-25,2023,July,18:19:34,5,386.20,NaN,Books,Penguin Books,Non-Fiction,Excellent,Express,Cash,Pending,4,Science
1365,7287475,76667,Portsmouth,England,UK,21,Male,High,Regular,2023-04-15,2023,April,04:25:08,<NA>,229.66,229.66,Clothing,Nike,Shorts,Good,Express,Credit Card,Pending,3,Swim trunks
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298416,1856172,76903,Halifax,Ontario,Canada,44,Male,Medium,Premium,2023-03-31,2023,March,21:32:30,<NA>,102.75,513.75,Electronics,Samsung,Television,Excellent,Express,Credit Card,Processing,5,LCD TV
298625,5250531,47928,Toowoomba,New South Wales,Australia,69,Male,High,New,2023-06-04,2023,June,03:45:16,<NA>,479.69,4317.25,Electronics,Samsung,Tablet,Average,Express,Credit Card,Pending,2,Samsung Galaxy Tab
299014,1703496,40106,Wuppertal,Berlin,Germany,60,Female,Medium,Regular,2023-08-20,2023,August,18:13:10,6,155.15,NaN,Home Decor,Home Depot,Tools,Bad,Express,Credit Card,Delivered,1,Utility knife
299123,9145097,18745,Leicester,England,UK,24,Male,Low,Regular,2024-02-05,2024,February,16:27:29,<NA>,160.44,320.88,Books,HarperCollins,Fiction,Bad,Express,Credit Card,Pending,1,Adventure
299305,3665915,37027,Long Beach,California,USA,60,Female,Low,Premium,2023-09-03,2023,September,03:42:18,4,458.46,NaN,Clothing,Adidas,T-shirt,Good,Express,Credit Card,Delivered,3,Long-sleeve tee

In [ ]:
# Ensure numeric
cols = ['Total_Purchases', 'Amount', 'Total_Amount']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')

# Convert purchases to float for calculation
df['Total_Purchases'] = df['Total_Purchases'].astype('float64')

# Fill missing values

# Case 1: Fill Total_Purchases
mask = df['Total_Purchases'].isna() & df['Total_Amount'].notna() & df['Amount'].notna() & (df['Amount'] != 0)
df.loc[mask, 'Total_Purchases'] = df.loc[mask, 'Total_Amount'] / df.loc[mask, 'Amount']

# Case 2: Fill Amount
mask = df['Amount'].isna() & df['Total_Amount'].notna() & df['Total_Purchases'].notna() & (df['Total_Purchases'] != 0)
df.loc[mask, 'Amount'] = df.loc[mask, 'Total_Amount'] / df.loc[mask, 'Total_Purchases']

# Case 3: If both missing → use median
df['Amount'].fillna(df['Amount'].median(), inplace=True)
df['Total_Purchases'].fillna(df['Total_Purchases'].median(), inplace=True)

# FINAL CONSISTENCY FIX

# Round purchases to integer
df['Total_Purchases'] = df['Total_Purchases'].round().astype('Int64')

# Recalculate Total_Amount
df['Amount'] = df['Amount'].round(2)
df['Total_Amount'] = (df['Amount'] * df['Total_Purchases']).round(2)

/tmp/ipykernel_5015/733097215.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Amount'].fillna(df['Amount'].median(), inplace=True)
/tmp/ipykernel_5015/733097215.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Total_Purchases'].fillna(df['Total_Purchases'].median(), inplace=True)

In [ ]:
# Fix Datetime columns
df = df.dropna(subset=['Date'])

df['Year'] = df['Date'].dt.year.astype('Int64')
df['Month'] = df['Date'].dt.month_name()

df['Time'] = df['Time'].fillna('00:00:00')
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S', errors='coerce').dt.time

### **Validate & Verify**

In [ ]:
# Final null check
df.isnull().sum()

Transaction_ID      0
Customer_ID         0
City                0
State               0
Country             0
Age                 0
Gender              0
Income              0
Customer_Segment    0
Date                0
Year                0
Month               0
Time                0
Total_Purchases     0
Amount              0
Total_Amount        0
Product_Category    0
Product_Brand       0
Product_Type        0
Feedback            0
Shipping_Method     0
Payment_Method      0
Order_Status        0
Ratings             0
products            0
dtype: int64

In [ ]:
# Shape check
df.shape

(293468, 25)

In [ ]:
# Datatype confirmation
df.dtypes

Transaction_ID               Int64
Customer_ID                  Int64
City                      category
State                     category
Country                   category
Age                          Int64
Gender                    category
Income                    category
Customer_Segment          category
Date                datetime64[ns]
Year                         Int64
Month                       object
Time                        object
Total_Purchases              Int64
Amount                     float64
Total_Amount               Float64
Product_Category          category
Product_Brand             category
Product_Type              category
Feedback                  category
Shipping_Method           category
Payment_Method            category
Order_Status              category
Ratings                      Int64
products                  category
dtype: object

In [ ]:
# Duplicate check
df.duplicated().sum()

np.int64(0)

In [ ]:
# Final validation

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 293468 entries, 0 to 299656
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    293468 non-null  Int64
 1   Customer_ID       293468 non-null  Int64
 2   City              293468 non-null  category
 3   State             293468 non-null  category
 4   Country           293468 non-null  category
 5   Age               293468 non-null  Int64
 6   Gender            293468 non-null  category
 7   Income            293468 non-null  category
 8   Customer_Segment  293468 non-null  category
 9   Date              293468 non-null  datetime64[ns]
 10  Year              293468 non-null  Int64
 11  Month             293468 non-null  object
 12  Time              293468 non-null  object
 13  Total_Purchases   293468 non-null  Int64
 14  Amount            293468 non-null  float64
 15  Total_Amount      293468 non-null  Float64
 16  Product_Category  293468 non-null  category
 17  Product_Brand     293468 non-null  category
 18  Product_Type      293468 non-null  category
 19  Feedback          293468 non-null  category
 20  Shipping_Method   293468 non-null  category
 21  Payment_Method    293468 non-null  category
 22  Order_Status      293468 non-null  category
 23  Ratings           293468 non-null  Int64
 24  products          293468 non-null  category
dtypes: Float64(1), Int64(6), category(14), datetime64[ns](1), float64(1), object(2)
memory usage: 33.3+ MB

Transaction_ID      0
Customer_ID         0
City                0
State               0
Country             0
Age                 0
Gender              0
Income              0
Customer_Segment    0
Date                0
Year                0
Month               0
Time                0
Total_Purchases     0
Amount              0
Total_Amount        0
Product_Category    0
Product_Brand       0
Product_Type        0
Feedback            0
Shipping_Method     0
Payment_Method      0
Order_Status        0
Ratings             0
products            0
dtype: int64

In [ ]:
# Export final file
df.to_csv('cleaned_dataset.csv', index=False)